### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by Signynt** [scottwillmoore/obsidian-short-internal-links-to-headings#2]
Thanks for taking the time to update things for Live Preview!

I've found some exceptions where it will not shorten the link in Live Preview:

1. When the link is in a bullet point:

```
- [[File#Heading]]
```

2. When the text has formatting applied (no matter what type):

```
*Sentence [[File#Heading]] with formatting*
```

3. When the link is in a block quote:

```
> [[File#Heading]]
```

**Comment by scottwillmoore** [comment]
I think this issue should be now fixed in [1.0.1](https://github.com/scottwillmoore/obsidian-short-internal-links-to-headings/releases/tag/1.0.1)! Please let me know if you encounter any more edge cases.

The only other edge case that I am aware of that isn't fixed at the moment is when links are used in [mermaid diagrams](https://help.obsidian.md/How+to/Format+your+notes#Diagram).
